version: '3.5'

services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env_mongo # Get MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - 27016:27017

# docker compose up -d
