GET http://localhost:8080/

###

GET http://localhost:8080/members

###

GET http://localhost:8080/members/1

###

POST http://localhost:8080/members

{
    "name": "John Doe",
    "address": "Ulica",
    "email": "test@gmail.com"
}

###

PUT http://localhost:8080/members/65eec902a34fc56dd3e9981c

{
    "name": "John Doe 2"
}

###

DELETE  http://localhost:8080/members/65eec902a34fc56dd3e9981c
